version: '3'
services:

  postgres:
    image: postgres:14.5-alpine
    restart: always
    container_name: postgres_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    depends_on: 
      - postgres
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: maxsuel@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

  auth:
    depends_on: 
      - postgres
    build: ./auth
    container_name: node_auth
    restart: unless-stopped
    environment: 
      DB_HOST: postgres
      DB_NAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "3080:3000"
    volumes:
      - ./auth:/usr/src/app
    networks:
      - app-network

volumes:
  db-data:
  pgadmin-data:

networks:
  app-network:
    driver: bridge
